version: "3.8"

services:
  mysql:
    image: mysql:9.0.1
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - my_network
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: flask_backend
    volumes:
      - ./backend:/app
      - images_data:/cocinapp/uploads # Volumen para la persistencia de imágenes
    ports:
      - "5000:5000" # Expone el puerto 5000
    environment:
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      COPY_IMG_MYSQL: ${COPY_IMG_MYSQL}
      CORS_ORIGINS: ${CORS_ORIGINS}
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  images_data: # Volumen para almacenar imágenes de forma persistente
    driver: local
