version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flask_backend
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"  # Expone el puerto 5000
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER: backend_user
      DATABASE_PASSWORD: 2df9-W6Bo74NMv5Y!
      DATABASE_NAME: cocinappDB
      JWT_SECRET_KEY: jfei-3n_i3n4FF3_43r85mfoFSJwffdsPdfs!
    depends_on:
      - mysql
    networks:
      - my_network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: TFG_1lc39z64KA-SF9ZxGf8H84
      MYSQL_DATABASE: cocinappDB
      MYSQL_USER: backend_user
      MYSQL_PASSWORD: 2df9-W6Bo74NMv5Y!
    ports: 
      - "3306:3306" #eliminar para produccion
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
